/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package infolabassignment1;

import data.User;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author Felix Delali Adigbli
 */
public class viewUserProfile extends javax.swing.JPanel {

    /**
     * Creates new form viewUserProfile
     */
    User inputUser;
    File photo;
    byte[] image;
    String imagepath = ""; 
    ImageIcon myimage;
    public viewUserProfile(User givenUser) {
        initComponents();
        this.inputUser = givenUser;
        
       File photo = photo.getAbsoluteFile();
       String p = photo.getAbsolutePath();
       photoViewLabel.setIcon(myimage);
        
        
        populateFields();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLable = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        majorLabel = new javax.swing.JLabel();
        majorLabel1 = new javax.swing.JLabel();
        firstNameViewLabel = new javax.swing.JLabel();
        lastNameViewLabel = new javax.swing.JLabel();
        ageViewLabel = new javax.swing.JLabel();
        telephoneNumberViewLabel = new javax.swing.JLabel();
        emailViewLabel = new javax.swing.JLabel();
        addressViewLabel = new javax.swing.JLabel();
        cityViewLabel = new javax.swing.JLabel();
        countryViewLabel = new javax.swing.JLabel();
        majorViewLabel = new javax.swing.JLabel();
        telephoneNumberLabel = new javax.swing.JLabel();
        photoViewLabel = new javax.swing.JLabel();

        titleLable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLable.setText("Find user's details below:");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        ageLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ageLabel.setText("Age");

        emailLable.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        emailLable.setText("Email");

        addressLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        addressLabel.setText("Address");

        cityLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        cityLabel.setText("City");

        countryLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        countryLabel.setText("Country");

        majorLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        majorLabel.setText("Major");

        majorLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        majorLabel1.setText("Photo");

        firstNameViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        lastNameViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        ageViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        telephoneNumberViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        emailViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        addressViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        cityViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        countryViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        majorViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        telephoneNumberLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        telephoneNumberLabel.setText("Telephone Number");

        photoViewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(majorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephoneNumberViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(majorViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(339, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(majorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(580, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(titleLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(firstNameViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telephoneNumberViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(majorViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(majorLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(photoViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(96, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addComponent(emailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(countryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(majorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(340, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressViewLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageViewLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityViewLabel;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel countryViewLabel;
    private javax.swing.JLabel emailLable;
    private javax.swing.JLabel emailViewLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameViewLabel;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameViewLabel;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JLabel majorLabel1;
    private javax.swing.JLabel majorViewLabel;
    private javax.swing.JLabel photoViewLabel;
    private javax.swing.JLabel telephoneNumberLabel;
    private javax.swing.JLabel telephoneNumberViewLabel;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
    firstNameViewLabel.setText(inputUser.getFirstName());
    lastNameViewLabel.setText(inputUser.getLastName());
    //ageViewLabel.setText(String.valueOf(inputUser.getAge()));
    emailViewLabel.setText(inputUser.getEmail());
    addressViewLabel.setText(inputUser.getAddress());
    telephoneNumberViewLabel.setText(inputUser.getTelephoneNumber());
    cityViewLabel.setText(inputUser.getCity());
    countryViewLabel.setText(inputUser.getCountry());
    majorViewLabel.setText(inputUser.getMajor());
    

    
    
    }
    public ImageIcon setIcon(String m, byte[] image){    
        if (m != null){
            myimage  = new ImageIcon(m);
        }  else { 
            myimage = new ImageIcon(m);
}
        Image img1 = myimage.getImage(); 
        Image img2 = img1.getScaledInstance(photoViewLabel.getWidth(), photoViewLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2); 
        return i;
    }

    
}
